[workspace]
members = [
    "crates/*"
]

resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/codywallace/iati-crates"
homepage = "https://github.com/codywallace/iati-crates"
